### PR TITLE
Fixed padding issues with layout

### PR DESCRIPTION
**Pull request by Xavier893**
Default layout now sets the padding across the app, custom padding not needed for pages anymore

### CODE REVIEW

**Review by iwandejong — COMMENTED** [review]
Can the "Unknown" be fixed in some when no field is selected? (maybe a gray colour or so)
image

**Comment by iwandejong** [comment]
A skeleton in Logs View can also look cool: https://primevue.org/skeleton/#datatable

**Comment by Xavier893** [comment]
Screenshot 2024-08-22 at 08 18 50

Added the skeleton component when Logs are loading and changed the tag for health when a field isn't selected @iwandejong

**Comment by Xavier893** [comment]
How's this? @iwandejong 

image

**Comment by iwandejong** [comment]
Yeah perfect😂👌🏼

**Review by iwandejong — APPROVED** [review]

**Pull request merged**
