### PR TITLE
Removed unused component that may cause issues

### PR DESCRIPTION
**Pull request by Xavier893**
Did look at different accounts with no data and everything was working fine. Removed old FieldData component that was unused and may have caused the issues. This is a refactor into dev to get the stable working app into the base branch.

### CODE REVIEW

**Comment by iwandejong** [comment]
Have you also changed all the "user" stuff to "team" even if it was just the file names?

**Comment by iwandejong** [comment]
Also check to remove unused vitest files. See error:
`Error: Failed to resolve import "~/components/FieldData.vue" from "tests/integration/GetFields.spec.ts". Does the file exist?`

**Comment by Xavier893** [comment]
Didn't rename the files and api calls in this branch no, but will quickly do so for naming conventions. Testing file should be handled by testing side, was the component that had the old getRecent endpoints in it and could have caused the internal nuxt error. Integration folder doesn't exist on my branch

**Comment by Xavier893** [comment]
@iwandejong renamed files to match api namin conventions and new teams feature request

**Review by iwandejong — APPROVED** [review]

**Pull request merged**
